"""
=========================================================
Universal Prolog Generator
=========================================================

Generates executable SWI-Prolog programs.

• Generic
• Keeps ALL executable clauses
• Supports both Prolog rules and facts
• Removes duplicates
• No algorithm-specific assumptions

=========================================================
"""

import os


class PrologGenerator:

    def __init__(self, output_file="generated/best_rules.pl"):

        self.output_file = output_file

    # =====================================================

    def generate(self, hypothesis):

        os.makedirs(
            os.path.dirname(self.output_file),
            exist_ok=True
        )

        lines = []

        # --------------------------------------------------
        # Header
        # --------------------------------------------------

        lines.append("% =========================================")
        lines.append("% Generated by Human-in-the-Loop Neuro-Symbolic AI")
        lines.append("% =========================================")
        lines.append("")

        description = hypothesis.get(
            "description",
            "Unknown hypothesis"
        )

        lines.append(f"% Description : {description}")
        lines.append("")

        # --------------------------------------------------
        # Generic helper predicates
        # --------------------------------------------------

        lines.extend([

            "is_even(X) :-",
            "    integer(X),",
            "    0 is X mod 2.",
            "",

            "is_odd(X) :-",
            "    integer(X),",
            "    1 is X mod 2.",
            ""

        ])

        # --------------------------------------------------
        # Write ALL executable clauses
        # --------------------------------------------------

        clauses = []
        seen = set()

        for rule in hypothesis.get("rules", []):

            rule = self.normalize_rule(rule)

            if not self.valid_rule(rule):
                continue

            if rule in seen:
                continue

            seen.add(rule)
            clauses.append(rule)

        # fallback

        if not clauses:

            clauses.append(
                "transform(Input, Output) :- Output = Input."
            )

        lines.extend(clauses)

        with open(
            self.output_file,
            "w",
            encoding="utf-8"
        ) as f:

            f.write("\n".join(lines))

        return self.output_file

    # =====================================================

    def normalize_rule(self, rule):

        rule = str(rule).strip()

        if not rule:
            return ""

        if not rule.endswith("."):
            rule += "."

        return rule

    # =====================================================

    def valid_rule(self, rule):

        if not rule:
            return False

        if not rule.endswith("."):
            return False

        if "(" not in rule or ")" not in rule:
            return False

        # Accept BOTH Prolog facts and rules.
        # Facts:
        #    swap([A,B],[B,A]).
        #
        # Rules:
        #    transform(X,Y):-swap(X,Y).

        return True